services:
  webpulse_backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: webpulse_backend
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
    networks:
      - webpulse_backend_net

  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/app/logs
    networks:
      - webpulse_backend_net

networks:
  webpulse_backend_net:
    driver: bridge
