app:
  # mock [true, false] - Включает моковые ответы на запросы
  mock: false

    # log_level: [DEBUG, INFO, WARNING, ERROR]
  log_level: INFO

  # log_format: [text, json]
  log_format: json

  http_server:
    listen_addr: 0.0.0.0:8080
    read_timeout: 10s
    write_timeout: 10s
    idle_timeout: 10s

  http_client:
    timeout: 10s